version: '3'
services:
  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3001:3000"
    networks:
      - hnclone-network


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: "host"

networks:
  hnclone-network:
    external: true
